export {default as Blog} from './blog/blog'
export {default as Feature} from './feature/feature'
export {default as Footer} from './footer/footer'
export {default as Header} from './header/header'
export {default as Possibility} from './possibility/possibility'
export {default as WhatGPT3} from './what GPT-3/whatGPT3'